### ISSUE TITLE
css not working from audioplayer or affected by Vuetify?

### ISSUE THREAD

**Issue by lucasscheepers** [xinnks/xns-audio-player-simple#3]
Hi, I want to add this audioplayer plugin while I'm using Vuetify as a plugin for styling my webpage. I think something went wrong with the css files while they have their own styles?
Below my screenshot. Is it possible to fix this in my project in a way? Hope to hear from you! Love your plugin

![Screenshot 2020-03-27 at 14 21 17](https://user-images.githubusercontent.com/22372422/77760406-92b37200-7036-11ea-9147-394cf0cdaec7.png)

**Comment by xinnks** [comment]
Thanks for the appreciation. Can you assist me with steps to reproduce that? @lucasscheepers

**Comment by lucasscheepers** [comment]
Yeah sure!
- Create a Vuejs app: `vue create exampleApp`
- Go to your folder: `cd exampleApp`
- Add a router to the Vuejs app: `vue add router`
- Add Vuetify framework: `vue add vuetify`
- Then I added the dark pre-made layout source code to my App.vue: https://vuetifyjs.com/en/getting-started/pre-made-layouts/
- Deleted context in <v-content> and replaced it with <router-view/>
- Deleted context in <v-footer> and replaced it with your audio player plugin

**Comment by xinnks** [comment]
@lucasscheepers Just run `npm i xns-audio-player-simple` and you'll have the latest version with the fix.

**Comment by lucasscheepers** [comment]
great thanks man!
