### ISSUE TITLE
Media resource indicated by the src attribute or assigned media provider object was not suitable

### ISSUE THREAD

**Issue by lucasscheepers** [xinnks/xns-audio-player-simple#4]
Hi,

When I want to play my own songs at my own computer I get this error:
<img width="1091" alt="Screenshot 2020-04-09 at 14 23 15" src="https://user-images.githubusercontent.com/22372422/78894701-d910c400-7a6d-11ea-8619-f7233b4a4a65.png">

Which mediatype is allowed?
Or do you know how I get my songs on the internet like this:
https://jt2.z1.fm/f/bf/labrinth_-_vultures_(zvukoff.ru).mp3

Thank you for your time

**Comment by xinnks** [comment]
According to your error it seems you are serving your audio file with the Content-Type Header "text/html" instead of an audio mime type.

**Comment by xinnks** [comment]
@lucasscheepers I don't know how you've served your audio files, but you can do it with php. This can help - [PHP Built-in web server](https://www.php.net/manual/en/features.commandline.webserver.php).

So instead of an image only serving router, in your router you can add your audio file mime types e.g "mp3"
```php
<?php
// router.php
if (preg_match('/\.(?:png|jpg|jpeg|gif|mp3)$/', $_SERVER["REQUEST_URI"])) {
    return false;    // serve the requested resource as-is.
} else { 
    echo "<p>Welcome to PHP</p>";
}
?>
```

Then run your server: ` $ php -S localhost:8000 router.php`

**Comment by lucasscheepers** [comment]
Yeah it worked! Thanks a lot.
Still have one more question about the width:
It is not the correct width I want. It gives me an error that it has the wrong type (string). But the value I provide is not a String. Well, if you don't know why, maybe I can fix something in another way. Still need a width of 1920.

![Screenshot 2020-04-11 at 11 47 22](https://user-images.githubusercontent.com/22372422/79040726-de474d80-7bea-11ea-9992-330e83193b3f.png)

![Screenshot 2020-04-11 at 11 47 33](https://user-images.githubusercontent.com/22372422/79040729-e0a9a780-7bea-11ea-89af-2d0b452d1c92.png)

<img width="695" alt="Screenshot 2020-04-11 at 11 50 12" src="https://user-images.githubusercontent.com/22372422/79040730-e1423e00-7bea-11ea-9a81-839d86be8fb1.png">

**Comment by xinnks** [comment]
@lucasscheepers If you don't use "v-bind" or it's short form ":" in attributes, Vue usually processes the attribute value as string, try this:
```vue
<xns-audio-player-simple :playlist="playlist" :player-width="1366"></xns-audio-player-simple>
```

**Comment by lucasscheepers** [comment]
Oh yes of course..

**Comment by xinnks** [comment]
@lucasscheepers About the max plugin width, at the moment it's fixed at 1366px. I had planned on adding the capability for it to be fluid on a later date after the current version, just lacked the time to do so. At the moment it's a future feature/enhancement. #5

**Comment by lucasscheepers** [comment]
Sounds cool!
